# Generated by Django 4.0.5 on 2022-06-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socNetwork', '0002_posts_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='static/pfp/default.png', upload_to='static/pfp/'),
        ),
    ]
