# Generated by Django 4.0.5 on 2022-06-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socNetwork', '0003_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='poster_type',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
