# Generated by Django 4.0.5 on 2022-07-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socNetwork', '0004_posts_poster_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_info',
            field=models.CharField(default='Public', max_length=20),
        ),
    ]
